input: touch: ftm4: Fix memory overflow
When building with gcc 7.2, the compiler detects an overflow of an
array

drivers/input/touchscreen/lge/lgsic/touch_sw49408.c: In function 'sw49408_irq_runtime_engine_debug':
drivers/input/touchscreen/lge/lgsic/touch_sw49408.c:2814:3: error: 'memcpy' writing 120 bytes into a region of size 104
 overflows the destination [-Werror=stringop-overflow=]
   memcpy(&ocd_debug, &d->info.debug, sizeof(d->info.debug));
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors

OCD_SIZE is defined in
drivers/input/touchscreen/lge/lgsic/touch_sw49408_prd.h to be 104.
d->info.debug is a struct sw49408_touch_debug which is 120 bytes.  By
copying 120 bytes into ocd_debug you overflow the array and the
memcpy() arbitrary positions in the stack.  Define ocd_debug to be of
the appropriate size to prevent the overflow.

Bug: 78362414
Change-Id: I4bd32b98914e043b4d7f411365e2cdb32af6ddd6
Signed-off-by: Javi Merino <javi.merino@arm.com>
Signed-off-by: Steve Pfetsch <spfetsch@google.com>